### ISSUE TITLE
Dynamically size border based on terminal size

### ISSUE THREAD

**Issue by mvertescher** [mattkelly/snake-go#4]
Affects the difficulty of the game, but cool feature to have

**Comment by mattkelly** [comment]
Thought about this a little bit. It might be possible to do something fancy like scale the entire game (snake, food, etc) proportionally using termloop's pixel mode. I'd be pretty difficult, though.

I was just playing with pixel mode - seems like my terminal draws the [unicode lower half-block character](http://www.fileformat.info/info/unicode/char/2584/index.htm) funny (cc @JoelOtter maybe you've seen this) ?

![image](https://user-images.githubusercontent.com/248713/32991578-ec933592-cd0b-11e7-889c-4fe2ea6f82c1.png)
